services:
  - type: web
    name: arabat-server
    runtime: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
